### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by defrankland** [lestrrat-go/codegen#1]
This repo should have a license file added. I got an error from my build scan tool on a project that uses JWX (which in turn uses this package)

**Comment by defrankland** [comment]
@lestrrat any chance of adding a license to this repo?

**Comment by lestrrat** [comment]
didnt notice this issue. I always use MIT. I womder why it wasnt included. will do in a bit

**Comment by lestrrat** [comment]
done.

**Comment by lestrrat** [comment]
I probably should have explicitly tagged you: @defrankland

**Comment by defrankland** [comment]
Looks good, thank you @lestrrat!
